<?php

declare(strict_types=1);

namespace Aurora\Workflows\Tests\Unit;

use Aurora\Workflows\Workflow;
use Aurora\Workflows\WorkflowState;
use Aurora\Workflows\WorkflowTransition;
use PHPUnit\Framework\Attributes\CoversClass;
use PHPUnit\Framework\TestCase;

#[CoversClass(Workflow::class)]
final class WorkflowTest extends TestCase
{
    private function createEditorialWorkflow(): Workflow
    {
        $workflow = new Workflow([
            'id' => 'editorial',
            'label' => 'Editorial',
        ]);

        $workflow->addState(new WorkflowState('draft', 'Draft', 0));
        $workflow->addState(new WorkflowState('review', 'In Review', 1));
        $workflow->addState(new WorkflowState('published', 'Published', 2));
        $workflow->addState(new WorkflowState('archived', 'Archived', 3));

        $workflow->addTransition(new WorkflowTransition(
            id: 'submit',
            label: 'Submit for Review',
            from: ['draft'],
            to: 'review',
        ));
        $workflow->addTransition(new WorkflowTransition(
            id: 'publish',
            label: 'Publish',
            from: ['draft', 'review'],
            to: 'published',
        ));
        $workflow->addTransition(new WorkflowTransition(
            id: 'archive',
            label: 'Archive',
            from: ['published'],
            to: 'archived',
        ));
        $workflow->addTransition(new WorkflowTransition(
            id: 'send_back',
            label: 'Send Back to Draft',
            from: ['review'],
            to: 'draft',
        ));

        return $workflow;
    }

    // ---------------------------------------------------------------
    //  Entity basics
    // ---------------------------------------------------------------

    public function testEntityTypeId(): void
    {
        $workflow = new Workflow(['id' => 'editorial', 'label' => 'Editorial']);
        $this->assertSame('workflow', $workflow->getEntityTypeId());
    }

    public function testIdAndLabel(): void
    {
        $workflow = new Workflow(['id' => 'editorial', 'label' => 'Editorial']);
        $this->assertSame('editorial', $workflow->id());
        $this->assertSame('Editorial', $workflow->label());
    }

    public function testUuidIsAutoGenerated(): void
    {
        $workflow = new Workflow(['id' => 'editorial', 'label' => 'Editorial']);
        $this->assertNotEmpty($workflow->uuid());
    }

    // ---------------------------------------------------------------
    //  State management
    // ---------------------------------------------------------------

    public function testAddAndGetState(): void
    {
        $workflow = new Workflow(['id' => 'test', 'label' => 'Test']);
        $state = new WorkflowState('draft', 'Draft');

        $result = $workflow->addState($state);

        $this->assertSame($workflow, $result, 'addState should return $this for chaining');
        $this->assertSame($state, $workflow->getState('draft'));
    }

    public function testGetStateReturnsNullForUnknown(): void
    {
        $workflow = new Workflow(['id' => 'test', 'label' => 'Test']);
        $this->assertNull($workflow->getState('nonexistent'));
    }

    public function testHasState(): void
    {
        $workflow = $this->createEditorialWorkflow();

        $this->assertTrue($workflow->hasState('draft'));
        $this->assertTrue($workflow->hasState('published'));
        $this->assertFalse($workflow->hasState('nonexistent'));
    }

    public function testGetStates(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $states = $workflow->getStates();

        $this->assertCount(4, $states);
        $this->assertArrayHasKey('draft', $states);
        $this->assertArrayHasKey('review', $states);
        $this->assertArrayHasKey('published', $states);
        $this->assertArrayHasKey('archived', $states);
    }

    public function testRemoveState(): void
    {
        $workflow = $this->createEditorialWorkflow();

        $result = $workflow->removeState('archived');

        $this->assertSame($workflow, $result, 'removeState should return $this for chaining');
        $this->assertFalse($workflow->hasState('archived'));
        $this->assertCount(3, $workflow->getStates());
    }

    public function testRemoveStateCascadesToTransitionTarget(): void
    {
        $workflow = $this->createEditorialWorkflow();

        // Removing 'archived' should remove the 'archive' transition (to: archived).
        $workflow->removeState('archived');

        $this->assertFalse($workflow->hasTransition('archive'));
    }

    public function testRemoveStateCascadesToTransitionSource(): void
    {
        $workflow = $this->createEditorialWorkflow();

        // 'publish' transition has from: ['draft', 'review'].
        // Removing 'review' should:
        //   - remove 'submit' (from: ['review'] only -> becomes empty)
        //   - remove 'send_back' (from: ['review'] only -> becomes empty)
        //   - keep 'publish' but update from to just ['draft']
        $workflow->removeState('review');

        $this->assertFalse($workflow->hasTransition('submit'));
        $this->assertFalse($workflow->hasTransition('send_back'));

        $publish = $workflow->getTransition('publish');
        $this->assertNotNull($publish);
        $this->assertSame(['draft'], $publish->from);
    }

    public function testRemoveNonexistentStateIsNoop(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $statesBefore = $workflow->getStates();

        $workflow->removeState('nonexistent');

        $this->assertSame(\count($statesBefore), \count($workflow->getStates()));
    }

    // ---------------------------------------------------------------
    //  Transition management
    // ---------------------------------------------------------------

    public function testAddAndGetTransition(): void
    {
        $workflow = new Workflow(['id' => 'test', 'label' => 'Test']);
        $transition = new WorkflowTransition('publish', 'Publish', ['draft'], 'published');

        $result = $workflow->addTransition($transition);

        $this->assertSame($workflow, $result, 'addTransition should return $this for chaining');
        $this->assertSame($transition, $workflow->getTransition('publish'));
    }

    public function testGetTransitionReturnsNullForUnknown(): void
    {
        $workflow = new Workflow(['id' => 'test', 'label' => 'Test']);
        $this->assertNull($workflow->getTransition('nonexistent'));
    }

    public function testHasTransition(): void
    {
        $workflow = $this->createEditorialWorkflow();

        $this->assertTrue($workflow->hasTransition('submit'));
        $this->assertTrue($workflow->hasTransition('publish'));
        $this->assertFalse($workflow->hasTransition('nonexistent'));
    }

    public function testGetTransitions(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $transitions = $workflow->getTransitions();

        $this->assertCount(4, $transitions);
        $this->assertArrayHasKey('submit', $transitions);
        $this->assertArrayHasKey('publish', $transitions);
        $this->assertArrayHasKey('archive', $transitions);
        $this->assertArrayHasKey('send_back', $transitions);
    }

    public function testRemoveTransition(): void
    {
        $workflow = $this->createEditorialWorkflow();

        $result = $workflow->removeTransition('archive');

        $this->assertSame($workflow, $result, 'removeTransition should return $this for chaining');
        $this->assertFalse($workflow->hasTransition('archive'));
        $this->assertCount(3, $workflow->getTransitions());
    }

    public function testRemoveNonexistentTransitionIsNoop(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $transitionsBefore = $workflow->getTransitions();

        $workflow->removeTransition('nonexistent');

        $this->assertSame(\count($transitionsBefore), \count($workflow->getTransitions()));
    }

    // ---------------------------------------------------------------
    //  Valid transitions / transition allowed
    // ---------------------------------------------------------------

    public function testGetValidTransitionsFromDraft(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $valid = $workflow->getValidTransitions('draft');

        $this->assertCount(2, $valid);
        $this->assertArrayHasKey('submit', $valid);
        $this->assertArrayHasKey('publish', $valid);
    }

    public function testGetValidTransitionsFromReview(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $valid = $workflow->getValidTransitions('review');

        $this->assertCount(2, $valid);
        $this->assertArrayHasKey('publish', $valid);
        $this->assertArrayHasKey('send_back', $valid);
    }

    public function testGetValidTransitionsFromPublished(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $valid = $workflow->getValidTransitions('published');

        $this->assertCount(1, $valid);
        $this->assertArrayHasKey('archive', $valid);
    }

    public function testGetValidTransitionsFromArchived(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $valid = $workflow->getValidTransitions('archived');

        $this->assertCount(0, $valid);
    }

    public function testGetValidTransitionsFromUnknownState(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $valid = $workflow->getValidTransitions('nonexistent');

        $this->assertSame([], $valid);
    }

    public function testIsTransitionAllowed(): void
    {
        $workflow = $this->createEditorialWorkflow();

        $this->assertTrue($workflow->isTransitionAllowed('draft', 'review'));
        $this->assertTrue($workflow->isTransitionAllowed('draft', 'published'));
        $this->assertTrue($workflow->isTransitionAllowed('review', 'published'));
        $this->assertTrue($workflow->isTransitionAllowed('review', 'draft'));
        $this->assertTrue($workflow->isTransitionAllowed('published', 'archived'));
    }

    public function testIsTransitionNotAllowed(): void
    {
        $workflow = $this->createEditorialWorkflow();

        $this->assertFalse($workflow->isTransitionAllowed('draft', 'archived'));
        $this->assertFalse($workflow->isTransitionAllowed('published', 'draft'));
        $this->assertFalse($workflow->isTransitionAllowed('archived', 'draft'));
        $this->assertFalse($workflow->isTransitionAllowed('archived', 'published'));
        $this->assertFalse($workflow->isTransitionAllowed('nonexistent', 'draft'));
    }

    // ---------------------------------------------------------------
    //  Config serialization
    // ---------------------------------------------------------------

    public function testToConfig(): void
    {
        $workflow = $this->createEditorialWorkflow();
        $config = $workflow->toConfig();

        $this->assertSame('editorial', $config['id']);
        $this->assertSame('Editorial', $config['label']);
        $this->assertTrue($config['status']);

        // Check states serialization.
        $this->assertArrayHasKey('states', $config);
        $this->assertCount(4, $config['states']);
        $this->assertSame('Draft', $config['states']['draft']['label']);
        $this->assertSame(0, $config['states']['draft']['weight']);
        $this->assertSame('Published', $config['states']['published']['label']);
        $this->assertSame(2, $config['states']['published']['weight']);

        // Check transitions serialization.
        $this->assertArrayHasKey('transitions', $config);
        $this->assertCount(4, $config['transitions']);
        $this->assertSame('Submit for Review', $config['transitions']['submit']['label']);
        $this->assertSame(['draft'], $config['transitions']['submit']['from']);
        $this->assertSame('review', $config['transitions']['submit']['to']);
    }

    public function testToConfigEmptyWorkflow(): void
    {
        $workflow = new Workflow(['id' => 'empty', 'label' => 'Empty']);
        $config = $workflow->toConfig();

        $this->assertSame('empty', $config['id']);
        $this->assertSame([], $config['states']);
        $this->assertSame([], $config['transitions']);
    }

    // ---------------------------------------------------------------
    //  Hydration from config values
    // ---------------------------------------------------------------

    public function testConstructorHydratesStatesFromArray(): void
    {
        $workflow = new Workflow([
            'id' => 'editorial',
            'label' => 'Editorial',
            'states' => [
                'draft' => ['label' => 'Draft', 'weight' => 0],
                'published' => ['label' => 'Published', 'weight' => 1],
            ],
        ]);

        $this->assertCount(2, $workflow->getStates());
        $this->assertSame('Draft', $workflow->getState('draft')?->label);
        $this->assertSame('Published', $workflow->getState('published')?->label);
    }

    public function testConstructorHydratesTransitionsFromArray(): void
    {
        $workflow = new Workflow([
            'id' => 'editorial',
            'label' => 'Editorial',
            'transitions' => [
                'publish' => [
                    'label' => 'Publish',
                    'from' => ['draft'],
                    'to' => 'published',
                    'weight' => 0,
                ],
            ],
        ]);

        $this->assertCount(1, $workflow->getTransitions());
        $transition = $workflow->getTransition('publish');
        $this->assertNotNull($transition);
        $this->assertSame('Publish', $transition->label);
        $this->assertSame(['draft'], $transition->from);
        $this->assertSame('published', $transition->to);
    }

    public function testConstructorHydratesFromWorkflowStateObjects(): void
    {
        $state = new WorkflowState('draft', 'Draft', 5);
        $workflow = new Workflow([
            'id' => 'test',
            'label' => 'Test',
            'states' => [
                'draft' => $state,
            ],
        ]);

        $this->assertSame($state, $workflow->getState('draft'));
    }

    public function testConstructorHydratesFromWorkflowTransitionObjects(): void
    {
        $transition = new WorkflowTransition('publish', 'Publish', ['draft'], 'published');
        $workflow = new Workflow([
            'id' => 'test',
            'label' => 'Test',
            'transitions' => [
                'publish' => $transition,
            ],
        ]);

        $this->assertSame($transition, $workflow->getTransition('publish'));
    }

    // ---------------------------------------------------------------
    //  Round-trip: build -> toConfig -> reconstruct
    // ---------------------------------------------------------------

    public function testRoundTripThroughConfig(): void
    {
        $original = $this->createEditorialWorkflow();
        $config = $original->toConfig();

        $restored = new Workflow($config);

        $this->assertSame($original->id(), $restored->id());
        $this->assertSame($original->label(), $restored->label());
        $this->assertCount(\count($original->getStates()), $restored->getStates());
        $this->assertCount(\count($original->getTransitions()), $restored->getTransitions());

        // Verify individual states.
        foreach ($original->getStates() as $id => $state) {
            $restoredState = $restored->getState($id);
            $this->assertNotNull($restoredState, "State '$id' should exist after round-trip");
            $this->assertSame($state->label, $restoredState->label);
            $this->assertSame($state->weight, $restoredState->weight);
        }

        // Verify individual transitions.
        foreach ($original->getTransitions() as $id => $transition) {
            $restoredTransition = $restored->getTransition($id);
            $this->assertNotNull($restoredTransition, "Transition '$id' should exist after round-trip");
            $this->assertSame($transition->label, $restoredTransition->label);
            $this->assertSame($transition->from, $restoredTransition->from);
            $this->assertSame($transition->to, $restoredTransition->to);
            $this->assertSame($transition->weight, $restoredTransition->weight);
        }

        // Verify transition logic is preserved.
        $this->assertTrue($restored->isTransitionAllowed('draft', 'review'));
        $this->assertFalse($restored->isTransitionAllowed('archived', 'draft'));
    }

    // ---------------------------------------------------------------
    //  Replacing a state / transition
    // ---------------------------------------------------------------

    public function testAddStateReplacesExisting(): void
    {
        $workflow = new Workflow(['id' => 'test', 'label' => 'Test']);
        $workflow->addState(new WorkflowState('draft', 'Draft', 0));
        $workflow->addState(new WorkflowState('draft', 'Draft v2', 10));

        $this->assertCount(1, $workflow->getStates());
        $this->assertSame('Draft v2', $workflow->getState('draft')?->label);
        $this->assertSame(10, $workflow->getState('draft')?->weight);
    }

    public function testAddTransitionReplacesExisting(): void
    {
        $workflow = new Workflow(['id' => 'test', 'label' => 'Test']);
        $workflow->addTransition(new WorkflowTransition('publish', 'Publish', ['draft'], 'published'));
        $workflow->addTransition(new WorkflowTransition('publish', 'Publish v2', ['draft', 'review'], 'published', 5));

        $this->assertCount(1, $workflow->getTransitions());
        $transition = $workflow->getTransition('publish');
        $this->assertSame('Publish v2', $transition?->label);
        $this->assertSame(['draft', 'review'], $transition?->from);
        $this->assertSame(5, $transition?->weight);
    }
}
